export type BodySystem = {
  id: string;
  name: string;
  region: string;
  summary: string;
  common: string[];
  redFlags: string[];
  free: string[];
  protocol: string[];
  formula: string;
  citations: string[];
  tier: "free" | "pro" | "plus";
};

export const BODY_SYSTEMS: BodySystem[] = [
  {
    id: "brain",
    name: "Head & brain",
    region: "Head",
    summary: "Headache, fog, attention, and migraine live here. Most 'brain' complaints are sleep, hydration, vision strain, and blood pressure — not a mystery lesion.",
    common: ["Tension headache", "Migraine", "Brain fog", "Poor concentration", "Light sensitivity"],
    redFlags: ["Thunderclap headache", "Headache with fever and stiff neck", "New neurological deficit", "Head injury with vomiting"],
    free: [
      "Water, then food, then screens-off. Dehydration and skipped meals cause more headaches than people admit.",
      "20-20-20 for screens. Outdoor morning light for circadian anchoring (Walker; Huberman Lab notes on melanopsin).",
      "Log headache days on paper for two weeks before asking for a scan — pattern beats panic.",
      "If it is the worst headache of your life, or thunderclap, leave this page. Emergency care.",
    ],
    protocol: [
      "Log headache frequency, triggers, and menstrual cycle for 4 weeks before asking for imaging.",
      "Magnesium glycinate 200–400 mg at night is commonly discussed for tension/migraine prevention — only with clinician approval if you have kidney disease.",
      "If migraines are disabling, evidence-based preventives (beta blockers, CGRP agents, topiramate) require a prescriber. We outline the class, never a script.",
    ],
    formula: "If a branded CGRP injector is unavailable, clinicians often discuss the same mAb class, oral gepants, or older preventives. Lifestyle stack: regular sleep, no skipped meals, limit alcohol, treat neck load.",
    citations: ["IHS headache classification", "Why We Sleep — Matthew Walker", "NICE headache pathway"],
    tier: "free",
  },
  {
    id: "eyes",
    name: "Eyes & vision",
    region: "Head",
    summary: "Dryness, strain, and fluctuating clarity are usually environment and refractive error. Sudden vision loss is never a wait-and-see event.",
    common: ["Dry eyes", "Screen strain", "Floaters", "Blur at night"],
    redFlags: ["Sudden vision loss", "Curtain over vision", "Painful red eye with vomiting", "Flashes with a shower of new floaters"],
    free: [
      "Blink breaks, humidity, and a current refraction. Artificial tears without redness-reducers for dryness.",
      "The 20-20-20 rule: every 20 minutes, look 20 feet away for 20 seconds.",
      "Sudden vision loss, a curtain, or flashes with a shower of new floaters is emergency ophthalmology — not drops.",
      "Diabetes: annual dilated exam. New glasses will not treat retinopathy.",
    ],
    protocol: ["Annual exam after 40, sooner with diabetes. Blue-light glasses are weakly evidenced; distance and lighting matter more."],
    formula: "If a specific lubricating drop is out of stock, look for preservative-free hyaluronate or carboxymethylcellulose equivalents.",
    citations: ["AAO preferred practice patterns"],
    tier: "free",
  },
  {
    id: "ent",
    name: "Ears, nose, throat",
    region: "Head",
    summary: "Congestion, sore throat, and ear pressure are usually viral. Duration and one-sidedness are what separate clinic-now from rest-now.",
    common: ["Congestion", "Post-nasal drip", "Sore throat", "Ear fullness", "Tinnitus"],
    redFlags: ["Neck swelling with fever", "Drooling / can't swallow", "One-sided hearing collapse", "Unilateral bloody nasal discharge"],
    free: [
      "Saline rinse, steam, honey for cough in adults, rest. Antibiotics do not treat viral colds.",
      "Most colds last 7–10 days. Green mucus is not an automatic antibiotic.",
      "One-sided hearing collapse, drooling, or a neck that will not flex with fever: clinic now.",
      "Tinnitus: first hearing check, caffeine/alcohol log, and quiet — not a mystery supplement.",
    ],
    protocol: ["Allergic rhinitis: nasal steroid correctly aimed, daily, for 2 weeks. Tinnitus first-line is hearing check + CBT-informed sound therapy, not mystery supplements."],
    formula: "If a named nasal steroid is unavailable, other intranasal corticosteroids are typically interchangeable under pharmacist/clinician guidance.",
    citations: ["CDC antibiotic stewardship", "Cochrane honey for cough"],
    tier: "pro",
  },
  {
    id: "mouth",
    name: "Mouth, teeth, jaw",
    region: "Head",
    summary: "Oral inflammation is systemic inflammation. Jaw clenching is a sleep and stress signal as often as a dental one.",
    common: ["Bleeding gums", "Jaw tightness", "Mouth ulcers", "Bad breath", "Tooth sensitivity"],
    redFlags: ["Floor-of-mouth swelling", "Unexplained oral ulcer >2 weeks", "Facial swelling with fever"],
    free: [
      "Twice-daily fluoride brush, daily interdental cleaning, night-time spit-don't-rinse. Reduce grazing on sugar.",
      "Bleeding gums are inflammation, not a brushing personality. See a dentist, not a charcoal powder.",
      "Ulcers lasting more than two weeks, or floor-of-mouth swelling: do not wait.",
      "Jaw clenching often lives with sleep and stress. A night guard is a tool after an exam.",
    ],
    protocol: ["Periodontal disease associates with cardiovascular risk — treat the mouth, don't just add fish oil. Occlusal guard for clenching after a dental exam."],
    formula: "Chlorhexidine rinses are short-course tools, not daily forever. If a branded paste is missing, match fluoride ppm, not marketing.",
    citations: ["AHA oral health and CVD statements", "WHO oral health"],
    tier: "pro",
  },
  {
    id: "neck",
    name: "Neck & thyroid",
    region: "Neck",
    summary: "Neck pain is usually load and posture. Thyroid symptoms are systemic: energy, temperature, hair, cycle, heart rate.",
    common: ["Stiff neck", "Desk tension", "Swallowing awareness", "Heat/cold intolerance"],
    redFlags: ["Neck stiffness with fever and photophobia", "Rapidly growing neck mass", "Stridor"],
    free: [
      "Chin tucks, thoracic extension, screens at eye height. Check TSH with a clinician if fatigue + hair + temperature cluster.",
      "A new pillow is not a rehab plan. Walk, and take the chin off the sternum.",
      "Fever plus a neck that will not flex, or a rapidly growing mass: leave this page.",
      "Thyroid is bloodwork, not a supplement aisle. Do not start iodine megadoses.",
    ],
    protocol: ["Hypothyroid replacement is levothyroxine, dosed by a clinician. 'Natural desiccated' is not automatically superior (ATA). Neck rehab beats a new pillow."],
    formula: "If a brand of levothyroxine is on backorder, stay on the same generic manufacturer when possible — small TSH shifts happen at switches.",
    citations: ["ATA thyroid guidelines", "Outlive — Peter Attia (zone 2 + strength as metabolic base)"],
    tier: "pro",
  },
  {
    id: "heart",
    name: "Heart & vessels",
    region: "Chest",
    summary: "Prevention is lipids, blood pressure, fitness, sleep apnea, and not smoking. Pain that is exertional, crushing, or radiating is an emergency until proven otherwise.",
    common: ["Palpitations", "High blood pressure reading", "Ankle swelling", "Reduced stamina"],
    redFlags: ["Crushing chest pain", "Pain to arm/jaw with sweat or nausea", "Sudden one-sided weakness", "Fainting with exercise"],
    free: [
      "Know your numbers: BP, ApoB or LDL, glucose/A1c, waist. Walk daily. Stop smoking.",
      "Zone 2 you can talk through, most days you can spare. Stairs count.",
      "DASH / Mediterranean pattern. Sodium awareness if blood pressure is the story.",
      "Crushing chest pain, pain to arm or jaw with sweat: emergency, not a website.",
    ],
    protocol: [
      "Peter Attia and AHA converge: ApoB is a better risk particle than LDL-C alone.",
      "Zone 2 cardio 3×/week + VO2 max work. DASH / Mediterranean pattern (PREDIMED).",
      "Statins, antihypertensives, and antiplatelets are clinician tools with enormous outcome data — never start from a website.",
    ],
    formula: "If a brand-name statin is unavailable, the molecule (atorvastatin, rosuvastatin, etc.) is what matters. Dose and liver/muscle monitoring stay with your clinician.",
    citations: ["AHA/ACC cholesterol guideline", "PREDIMED", "Outlive — Attia", "Framingham / MESA risk literature"],
    tier: "free",
  },
  {
    id: "lungs",
    name: "Lungs & breath",
    region: "Chest",
    summary: "Airway irritability, deconditioning, and anxiety all feel like 'I can't get a full breath.' True hypoxia, hemoptysis, or one-sided pain after travel is different.",
    common: ["Wheeze", "Cough >2 weeks", "Air hunger at rest", "Exercise cough"],
    redFlags: ["Blue lips", "Coughing blood", "Sudden chest pain with breathlessness", "High fever with rusty sputum"],
    free: [
      "Nasal breathing at rest, slow exhale (4–6 breaths/min) for CO2 tolerance. Do not ignore a 3-week cough.",
      "If you smoke: stopping outperforms almost every other lever. Licensed cessation exists.",
      "Blue lips, coughing blood, or sudden one-sided chest pain: emergency.",
      "Asthma that needs a rescue inhaler weekly is under-treated — that is a clinician conversation.",
    ],
    protocol: ["Asthma: inhaled corticosteroid is controller, not only a rescue inhaler. Smoking cessation pharmacotherapy is first-line with counseling."],
    formula: "If a branded inhaler is shorted, pharmacies and clinicians map to equivalent ICS/LABA molecules. Never stretch a rescue inhaler as your only plan.",
    citations: ["GINA asthma", "GOLD COPD"],
    tier: "pro",
  },
  {
    id: "gut",
    name: "Gut & digestion",
    region: "Abdomen",
    summary: "Bloating, reflux, and irregularity are common. Pattern, blood, weight loss, and night pain decide urgency. Fiber and fermented foods beat most powders.",
    common: ["Bloating", "Reflux", "Constipation", "Loose stools", "Food fear"],
    redFlags: ["Black stools or blood", "Unexplained weight loss", "Persistent vomiting", "Jaundice", "Severe sudden abdominal pain"],
    free: [
      "30 plants/week, water, and a regular meal rhythm. Elevate the head of the bed for night reflux. Don't lie down after eating.",
      "A 10-minute walk after meals. Chew. Don't graze from 9pm.",
      "Blood in stool, black stools, or unexplained weight loss: clinic, not a new powder.",
    ],
    protocol: [
      "IBS: low-FODMAP is a short diagnostic diet, not a personality. Reintroduce with a dietitian.",
      "PPI for reflux is effective short-term; long-term needs a reason (ACG).",
      "H. pylori testing when ulcer-type pain or uninvestigated dyspepsia in the right age/region.",
    ],
    formula: "If a branded PPI is unavailable, omeprazole/esomeprazole/lansoprazole are the same class. Pair with deprescribing plan, not infinite use.",
    citations: ["ACG GERD guideline", "Rome IV IBS", "Fiber and microbiome reviews — Sonnenburg"],
    tier: "free",
  },
  {
    id: "metabolic",
    name: "Liver, pancreas, metabolism",
    region: "Abdomen",
    summary: "This is the modern epidemic layer: insulin resistance, fatty liver, triglycerides. Waist and fitness predict more than willpower speeches.",
    common: ["Central weight", "Sugar crashes", "Elevated enzymes", "Skin tags", "Fatty liver on scan"],
    redFlags: ["Confusion with jaundice", "Severe upper pain radiating to back with vomiting", "Ketotic breathing in a diabetic"],
    free: ["Protein at each meal, walk 10 minutes after eating, resistance training. Cut sugar-sweetened drinks first."],
    protocol: [
      "A1c, fasting insulin or OGTT, ALT, triglycerides, waist. NAFLD reverses with 7–10% weight loss and zone 2.",
      "GLP-1 agonists and metformin are clinician-prescribed tools with trial data — not DIY peptides.",
    ],
    formula: "If a branded GLP-1 is unavailable, shortages are common; clinicians may bridge with another incretin or intensify lifestyle + metformin. Compounded copies are a safety minefield — prefer licensed supply.",
    citations: ["ADA Standards of Care", "EASL NAFLD", "Look AHEAD / DPP trials"],
    tier: "plus",
  },
  {
    id: "kidney",
    name: "Kidneys & urinary",
    region: "Abdomen",
    summary: "Silent until they aren't. Blood pressure, diabetes, and NSAID overuse are the usual villains. Burning urine is often infection — flank pain with fever is pyelonephritis territory.",
    common: ["Frequency", "Urgency", "Night urination", "Foamy urine"],
    redFlags: ["Fever with flank pain", "Inability to pass urine", "Blood in urine with clots", "Ankle swelling with low urine output"],
    free: ["Don't chronically high-dose ibuprofen. Hydrate. Treat BP. Cranberry is modest for recurrent UTI prevention, not a cure."],
    protocol: ["eGFR and urine albumin. Men with incomplete emptying need prostate evaluation. Women with recurrent UTI need a plan, not endless emergency antibiotics."],
    formula: "If a named antibiotic is unavailable, culture-guided alternatives exist — never repeat the last leftover pill.",
    citations: ["KDIGO CKD", "IDSA UTI"],
    tier: "pro",
  },
  {
    id: "hormone",
    name: "Hormones & reproductive",
    region: "Pelvis",
    summary: "Cycles, fertility, androgens, menopause, and testosterone are labs plus life context. Fatigue is not automatically 'low T' or 'adrenal fatigue' — the latter is not a medical diagnosis.",
    common: ["Irregular cycles", "PMS", "Low libido", "Hot flashes", "Acne / hair change"],
    redFlags: ["Positive pregnancy test with severe pain or bleeding", "Testicular pain", "Post-menopausal bleeding"],
    free: ["Track cycle, sleep, iron-rich food, and strength. Under-fueling destroys hormones in all sexes."],
    protocol: [
      "PCOS: weight-bearing training, protein, and insulin-sensitizing care per Endocrine Society.",
      "Menopause: shared decision on HRT — timing and clot/breast history matter (NAMS).",
      "Male hypogonadism: two morning total T levels, not a social-media protocol.",
    ],
    formula: "If a branded estradiol/progesterone or testosterone gel is unavailable, bioequivalent licensed preparations exist. Avoid unregulated 'wellness pellets' without monitoring.",
    citations: ["Endocrine Society PCOS", "NAMS 2022 hormone therapy", "AUA testosterone"],
    tier: "plus",
  },
  {
    id: "msk",
    name: "Muscle, joint, bone",
    region: "Frame",
    summary: "Most pain is mechanical and trainable. Red flags are infection, fracture, cancer history, and cord compression. Bone is a use-it tissue.",
    common: ["Low back pain", "Knee grind", "Shoulder pinch", "Desk stiffness", "Sarcopenia"],
    redFlags: ["Saddle anesthesia", "Loss of bladder/bowel", "Hot swollen joint", "Night bone pain with weight loss"],
    free: [
      "Walk, then load. 2–3 full-body strength sessions. Protein ~1.6 g/kg if training and kidneys are well (with clinician if CKD).",
      "Most back pain is mechanical. Keep walking. Imaging is for red flags (Choosing Wisely).",
      "Hot swollen joint, saddle anesthesia, or night bone pain with weight loss: not a foam roller.",
    ],
    protocol: [
      "ACSM: strength 2+ days, balance, and impact for bone.",
      "Back pain: keep moving; imaging is for red flags (Choosing Wisely).",
      "Vitamin D if deficient; calcium from food first.",
    ],
    formula: "If a branded NSAID gel is unavailable, diclofenac topical generics and relative rest + loading are the actual medicine. Opioids are last, not first.",
    citations: ["ACSM guidelines", "Choosing Wisely imaging", "Lancet low back pain series"],
    tier: "free",
  },
  {
    id: "skin",
    name: "Skin, hair, nails",
    region: "Surface",
    summary: "Barrier, inflammation, hormones, and sun. Changing moles are a dermatology visit. Hair shedding after stress or fever is often telogen effluvium — temporary.",
    common: ["Acne", "Eczema", "Dandruff", "Hair shed", "Brittle nails"],
    redFlags: ["Changing mole (ABCDE)", "Rapidly spreading red skin with fever", "Blistering drug rash"],
    free: [
      "Gentle cleanser, moisturizer, SPF. Don't pick. Iron and protein if shedding plus fatigue.",
      "Adapalene at night, benzoyl peroxide as a spot, six weeks before judging. Irritation is not a glow.",
      "Changing moles (ABCDE) are a dermatologist, not a serum. Photograph them in the same light.",
      "Rapidly spreading red skin with fever, or blistering after a new drug: urgent care.",
    ],
    protocol: ["Retinoids and benzoyl peroxide remain acne foundations. Biologics for psoriasis are specialist care with extraordinary evidence."],
    formula: "If a branded retinoid is unavailable, adapalene 0.1% OTC is a close cousin. Compounded 'skin stacks' should still use known actives and concentrations.",
    citations: ["AAD acne", "AAD melanoma"],
    tier: "pro",
  },
  {
    id: "immune",
    name: "Immune & inflammation",
    region: "Whole",
    summary: "Frequent colds are often sleep, contacts, and coincidence. Autoimmune disease is specific, serologic, and not diagnosed by a social-media panel of 90 markers.",
    common: ["Frequent colds", "Slow recovery", "Aches after illness", "Allergies"],
    redFlags: ["Anaphylaxis", "High fever in an immunocompromised person", "Unexplained fevers with night sweats and weight loss"],
    free: [
      "Vaccines you are due for. Sleep. Don't mega-dose vitamin C. Zinc lozenges have mixed, modest cold-duration data if taken early.",
      "Frequent colds are often contacts, children, and sleep — not a hidden immune collapse.",
      "Anaphylaxis: epinephrine first, then emergency services. This site cannot hold that.",
      "Unexplained fevers with night sweats and weight loss: a clinician, not a 'wellness panel' of 90 markers.",
    ],
    protocol: ["CRP/ferritin in context, not isolation. Autoimmune workups belong with a clinician. Exercise is an anti-inflammatory drug with a dose-response."],
    formula: "If a branded antihistamine is unavailable, second-generation options (cetirizine, loratadine, fexofenadine) are interchangeable for many people.",
    citations: ["CDC immunization", "Physical activity guidelines — anti-inflammatory effects"],
    tier: "pro",
  },
  {
    id: "mind",
    name: "Mood, anxiety, attention",
    region: "Mind",
    summary: "Mental suffering is medical. Therapy, sleep, movement, substances, and sometimes medication are the evidence stack. You are not weak for needing all of them.",
    common: ["Worry loops", "Low mood", "Panic", "Inattention", "Irritability", "Numbness"],
    redFlags: [
      "Thoughts of suicide or self-harm — call 988 (US) or local emergency services now",
      "Mania",
      "Psychosis",
      "Inability to care for self",
    ],
    free: [
      "Sleep regularity, daylight, 20 minutes of brisk walking, and fewer than 7 drinks a week change mood biology.",
      "If you are in crisis: 988 Suicide & Crisis Lifeline (US) or your local emergency number.",
    ],
    protocol: [
      "CBT, behavioral activation, and interpersonal therapy have effect sizes comparable to medication for many mild-moderate depressions (NICE, APA).",
      "Medication (SSRIs etc.) is a clinical decision. We will discuss classes educationally, never start/stop them for you.",
      "ADHD in adults: structured environment + formal assessment. Stimulants are controlled medicines.",
    ],
    formula: "If a branded SSRI is unavailable, the molecule usually has a generic. Switching requires a clinician because of discontinuation and interaction effects. Do not cold-turkey.",
    citations: ["NICE depression", "The Body Keeps the Score — van der Kolk (trauma context)", "Feeling Good — Burns (CBT)", "988 lifeline"],
    tier: "free",
  },
  {
    id: "pelvis",
    name: "Pelvis, cycle, sexual health",
    region: "Pelvis",
    summary: "Cycles, pelvic pain, urinary symptoms, and sexual function are medical. Shame is not a protocol. Sudden severe pelvic pain is not a website.",
    common: ["Painful periods", "Pelvic tightness", "UTIs that recur", "Low desire", "Perimenopause heat"],
    redFlags: [
      "Sudden severe pelvic or testicular pain",
      "Heavy bleeding soaking a pad hourly",
      "Pregnancy with bleeding or one-sided pain",
      "Fever with flank pain",
    ],
    free: [
      "Track the cycle if you have one — pattern is data. Pain that stops life is not 'just periods.'",
      "Hydration and not delaying urination for recurrent simple UTIs; fever or flank pain is kidney until proven otherwise.",
      "Perimenopause: sleep, strength, and a clinician for hormones — not an Instagram pellet clinic.",
      "Sexual pain or loss of function: a licensed clinician. This desk names the door.",
    ],
    protocol: [
      "Dysmenorrhea first-line is often heat, NSAIDs timed before pain peaks, and a conversation about the pill or IUD with a prescriber.",
      "Recurrent UTI needs culture, not a cranberry subscription. Post-menopausal genitourinary syndrome is treatable.",
      "Testosterone and menopause hormones are specialist conversations (NAMS, Endocrine Society), not a protocol you copy from a feed.",
    ],
    formula: "If a branded combined pill is unavailable, equivalent ethinylestradiol + progestin pills exist — switching still belongs with a prescriber. Local vaginal estrogen, if prescribed, is a different tool from systemic HRT.",
    citations: ["NAMS menopause", "ACOG dysmenorrhea", "IDSA UTI", "Endocrine Society testosterone"],
    tier: "free",
  },
  {
    id: "circulation",
    name: "Circulation, blood, clotting",
    region: "Vessels",
    summary: "Swelling, bruising, cold hands, and clots. Most 'poor circulation' is deconditioning, smoking, or sitting. A hot swollen calf after travel is not a stretch.",
    common: ["Cold fingers", "Easy bruising", "Ankle swelling at day's end", "Varicose ache"],
    redFlags: [
      "One-sided hot swollen calf",
      "Sudden shortness of breath after travel or surgery",
      "Unexplained bruising with pale fatigue",
      "Black painful toes",
    ],
    free: [
      "Walk. Calf raises at the desk. Compression if a clinician has named venous disease — not because an ad said so.",
      "Smoking plus the pill plus immobility is a clot conversation, not a vibe.",
      "Iron deficiency is common and tired. Ferritin belongs with a clinician if shedding, pica, or heavy periods cluster.",
      "One-sided hot calf or sudden breathlessness after a flight: emergency.",
    ],
    protocol: [
      "DVT/PE are diagnosed, not guessed. Do not start or stop anticoagulants from a website.",
      "Anemia workup is iron studies plus the reason for the loss. B12 if vegan or gastric surgery.",
      "PAD: walking programme plus risk-factor clinic. Pain at rest or tissue loss is urgent.",
    ],
    formula: "If a branded anticoagulant is shorted, the molecule and indication matter more than the box. Never substitute from a website. Iron salts differ in elemental iron — a pharmacist maps them.",
    citations: ["ASH venous thromboembolism", "AHA PAD", "WHO anemia", "NICE VTE"],
    tier: "free",
  },
];
