export type Source = {
  id: string;
  title: string;
  author: string;
  kind: "book" | "guideline" | "trial" | "lecture";
  year: string;
  takeaway: string;
  usedIn: string[];
  tier: "free" | "pro" | "plus";
};

export const LIBRARY: Source[] = [
  {
    id: "walker",
    title: "Why We Sleep",
    author: "Matthew Walker",
    kind: "book",
    year: "2017",
    takeaway:
      "Sleep is not optional recovery. Short sleep impairs glucose, immunity, emotion, and accident risk. Regularity beats weekend catch-up.",
    usedIn: ["Sleep", "Mind", "Clinic"],
    tier: "free",
  },
  {
    id: "attia",
    title: "Outlive",
    author: "Peter Attia",
    kind: "book",
    year: "2023",
    takeaway:
      "Medicine 3.0: delay the Four Horsemen with VO2 max, strength, stability, ApoB, and metabolic health — not waiting for disease.",
    usedIn: ["Strength", "Fuel", "Clinic"],
    tier: "free",
  },
  {
    id: "clear",
    title: "Atomic Habits",
    author: "James Clear",
    kind: "book",
    year: "2018",
    takeaway: "Identity plus environment design outperform motivation. Make the cue obvious, the action easy, the reward satisfying.",
    usedIn: ["Discipline", "Time"],
    tier: "free",
  },
  {
    id: "newport",
    title: "Deep Work",
    author: "Cal Newport",
    kind: "book",
    year: "2016",
    takeaway: "Focus is trainable. Time-block the cognitively hard work; shallow work expands to fill the unguarded day.",
    usedIn: ["Mind", "Career"],
    tier: "free",
  },
  {
    id: "kahneman",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    kind: "book",
    year: "2011",
    takeaway: "System 1 is fast and biased; System 2 is lazy. Intelligence includes noticing when to slow down.",
    usedIn: ["Mind", "Intelligence"],
    tier: "free",
  },
  {
    id: "frankl",
    title: "Man's Search for Meaning",
    author: "Viktor Frankl",
    kind: "book",
    year: "1946",
    takeaway: "Purpose is chosen under constraint. Suffering with meaning is different from suffering without it.",
    usedIn: ["Purpose"],
    tier: "free",
  },
  {
    id: "predimed",
    title: "PREDIMED",
    author: "Estruch et al., NEJM",
    kind: "trial",
    year: "2013/2018",
    takeaway: "Mediterranean pattern plus olive oil or nuts reduced major cardiovascular events versus a low-fat advice control.",
    usedIn: ["Fuel", "Kitchen"],
    tier: "free",
  },
  {
    id: "acsm",
    title: "ACSM exercise guidelines",
    author: "American College of Sports Medicine",
    kind: "guideline",
    year: "current",
    takeaway: "150–300 min moderate aerobic, plus ≥2 days muscle, plus balance with age. Strength is not optional after 40.",
    usedIn: ["Strength"],
    tier: "free",
  },
  {
    id: "nami",
    title: "When to involve a therapist",
    author: "APA / NAMI guidance",
    kind: "guideline",
    year: "current",
    takeaway:
      "If function is dropping, symptoms last >2 weeks, relationships are harming you, or you have trauma loops — skilled therapy is indicated, not a luxury.",
    usedIn: ["Relations", "Mind"],
    tier: "free",
  },
  {
    id: "gottman",
    title: "The Seven Principles for Making Marriage Work",
    author: "John Gottman",
    kind: "book",
    year: "1999",
    takeaway: "Bids for connection, 5:1 positive-to-negative, and turning toward. Contempt is the acid.",
    usedIn: ["Relations"],
    tier: "free",
  },
  {
    id: "holt",
    title: "Loneliness and mortality",
    author: "Holt-Lunstad et al.",
    kind: "trial",
    year: "2010/2015",
    takeaway: "Weak social connection is a mortality risk on the order of well-known clinical factors. Loneliness is physiology, not drama.",
    usedIn: ["Relations", "Clinic"],
    tier: "free",
  },
  {
    id: "dpp",
    title: "Diabetes Prevention Program",
    author: "Knowler et al.",
    kind: "trial",
    year: "2002",
    takeaway: "Lifestyle (≈7% weight loss + 150 min activity) beat metformin for preventing diabetes in high-risk adults — both beat placebo.",
    usedIn: ["Fuel", "Clinic"],
    tier: "free",
  },
  {
    id: "morton",
    title: "Protein and resistance training",
    author: "Morton et al., Br J Sports Med",
    kind: "trial",
    year: "2018",
    takeaway: "≈1.6 g/kg/day protein is a practical ceiling for most hypertrophy. More is rarely better; distribution across meals helps.",
    usedIn: ["Strength", "Fuel"],
    tier: "free",
  },
  {
    id: "qaseem",
    title: "ACP insomnia guideline",
    author: "Qaseem et al., Annals of Internal Medicine",
    kind: "guideline",
    year: "2016",
    takeaway: "CBT-I is first-line for chronic insomnia. Hypnotics can be a bridge. They are not a personality.",
    usedIn: ["Sleep"],
    tier: "free",
  },
  {
    id: "who-pa",
    title: "WHO physical activity guidelines",
    author: "World Health Organization",
    kind: "guideline",
    year: "2020",
    takeaway: "Some is better than none. Sitting less, moving more, and adding muscle work — globally, not as a boutique hobby.",
    usedIn: ["Strength", "World"],
    tier: "free",
  },
  {
    id: "gollwitzer",
    title: "Implementation intentions",
    author: "Peter Gollwitzer",
    kind: "lecture",
    year: "1999–",
    takeaway: "If-then plans ('If it is 7am, then shoes on') beat vague goals. Discipline is often just pre-decided geography.",
    usedIn: ["Discipline", "Time"],
    tier: "free",
  },
  {
    id: "burns",
    title: "Feeling Good",
    author: "David D. Burns",
    kind: "book",
    year: "1980",
    takeaway: "CBT in plain language: catch the distortion, write the alternative. Not a replacement for care when function collapses.",
    usedIn: ["Mind"],
    tier: "free",
  },
  {
    id: "harvard-plate",
    title: "Healthy Eating Plate",
    author: "Harvard T.H. Chan School of Public Health",
    kind: "guideline",
    year: "current",
    takeaway: "½ vegetables and fruit, ¼ whole grains, ¼ protein, water, healthy oils. The plate is the protocol.",
    usedIn: ["Fuel", "Kitchen"],
    tier: "free",
  },
  {
    id: "vanderkolk",
    title: "The Body Keeps the Score",
    author: "Bessel van der Kolk",
    kind: "book",
    year: "2014",
    takeaway: "Trauma lives in physiology. Talk is not always enough; body-based and evidence-based therapies matter.",
    usedIn: ["Mind", "Relations"],
    tier: "free",
  },
  {
    id: "goleman",
    title: "Emotional Intelligence",
    author: "Daniel Goleman",
    kind: "book",
    year: "1995",
    takeaway: "Self-awareness, self-regulation, empathy, and social skill predict life outcomes beyond IQ.",
    usedIn: ["Emotion", "Social"],
    tier: "free",
  },
  {
    id: "ericsson",
    title: "Peak",
    author: "Anders Ericsson",
    kind: "book",
    year: "2016",
    takeaway: "Deliberate practice with feedback, not logged hours, builds skill. Comfort is the enemy of improvement.",
    usedIn: ["Intelligence", "Strength"],
    tier: "free",
  },
  {
    id: "epstein",
    title: "Range",
    author: "David Epstein",
    kind: "book",
    year: "2019",
    takeaway: "In kind worlds, specialize. In wicked worlds (career, modern life), generalists who analogize win.",
    usedIn: ["Career"],
    tier: "pro",
  },
  {
    id: "huberman",
    title: "Huberman Lab (public protocols)",
    author: "Andrew Huberman",
    kind: "lecture",
    year: "2021–",
    takeaway: "Morning outdoor light, delayed caffeine, consistent sleep, light as a circadian drug. Education, not medical orders.",
    usedIn: ["Sleep", "Energy"],
    tier: "pro",
  },
  {
    id: "aha",
    title: "AHA/ACC cholesterol guideline",
    author: "American Heart Association",
    kind: "guideline",
    year: "2018+",
    takeaway: "Risk-based lipid therapy. ApoB-containing particles drive atherosclerosis. Lifestyle always; drugs when risk demands.",
    usedIn: ["Clinic"],
    tier: "plus",
  },
  {
    id: "choosing",
    title: "Choosing Wisely — imaging",
    author: "ABIM Foundation",
    kind: "guideline",
    year: "current",
    takeaway: "Don't image routine back pain without red flags. More scans can create more harm and more fear.",
    usedIn: ["Clinic"],
    tier: "plus",
  },
  {
    id: "burnett",
    title: "Designing Your Life",
    author: "Bill Burnett & Dave Evans",
    kind: "book",
    year: "2016",
    takeaway: "Prototype lives. Don't wait for passion; run small experiments on work and meaning.",
    usedIn: ["Career", "Purpose"],
    tier: "plus",
  },
  {
    id: "seneca",
    title: "Letters from a Stoic",
    author: "Seneca",
    kind: "book",
    year: "c. 65",
    takeaway: "Control the controllable. World events will not wait for your nervous system to feel ready.",
    usedIn: ["World", "Discipline"],
    tier: "plus",
  },
  {
    id: "dash",
    title: "DASH eating pattern",
    author: "NHLBI / Appel et al.",
    kind: "trial",
    year: "1997+",
    takeaway: "Dietary Approaches to Stop Hypertension: plants, low-fat dairy, less sodium — blood pressure drops without a speech.",
    usedIn: ["Fuel", "Clinic"],
    tier: "free",
  },
  {
    id: "aasm",
    title: "AASM insomnia / CBT-I",
    author: "American Academy of Sleep Medicine",
    kind: "guideline",
    year: "current",
    takeaway: "Stimulus control, sleep restriction (guided), and cognitive work. Wearables estimate; they do not diagnose apnea.",
    usedIn: ["Sleep"],
    tier: "pro",
  },
  {
    id: "who-pa",
    title: "WHO physical activity guidelines",
    author: "World Health Organization",
    kind: "guideline",
    year: "2020",
    takeaway: "150–300 minutes moderate aerobic plus two strength days. Some activity is vastly better than none. Sitting is the other dose.",
    usedIn: ["Strength", "Longevity"],
    tier: "free",
  },
  {
    id: "harvard-plate",
    title: "Healthy Eating Plate",
    author: "Harvard T.H. Chan School of Public Health",
    kind: "guideline",
    year: "2011+",
    takeaway: "Half vegetables and fruit, a quarter whole grain, a quarter protein, olive oil, water. The food-guide pyramid, retired with evidence.",
    usedIn: ["Fuel", "Kitchen"],
    tier: "free",
  },
  {
    id: "holt",
    title: "Loneliness as a vital sign",
    author: "Holt-Lunstad et al.",
    kind: "trial",
    year: "2010–2015",
    takeaway: "Social isolation predicts mortality on the order of smoking and obesity. Bond is physiology, not a personality type.",
    usedIn: ["Relations", "Longevity"],
    tier: "free",
  },
  {
    id: "nice-dep",
    title: "NICE depression in adults",
    author: "National Institute for Health and Care Excellence",
    kind: "guideline",
    year: "current",
    takeaway: "Guided self-help, CBT, behavioural activation, then medication with a clinician. Exercise is in the pathway. Crisis is emergency care.",
    usedIn: ["Mind", "Clinic"],
    tier: "free",
  },
];
