export type MedicineNote = {
  id: string;
  name: string;
  className: string;
  usedFor: string;
  how: string;
  avoid: string;
  ifUnavailable: string;
  cite: string;
};

export const MEDICINES: MedicineNote[] = [
  {
    id: "para",
    name: "Paracetamol / acetaminophen",
    className: "Simple analgesic",
    usedFor: "Headache, mild fever, musculoskeletal ache when inflammation is not the main story.",
    how: "Stay inside the labelled adult daily maximum. Combine sources (cold syrups) silently and overdose the liver.",
    avoid: "Liver disease, heavy alcohol, already taking a combination cold product. Not for children at adult doses.",
    ifUnavailable: "The molecule is what matters. Match the milligrams, not the brand. Ibuprofen is a different class — not a silent swap if you have ulcers, kidneys, or late pregnancy.",
    cite: "WHO essential medicines; FDA acetaminophen safety",
  },
  {
    id: "nsaid",
    name: "Ibuprofen / naproxen",
    className: "NSAID",
    usedFor: "Inflammatory pain (dental, menstrual, sprain) for short courses.",
    how: "With food. Shortest course that works. Topical NSAID gels for a joint can spare the gut.",
    avoid: "Ulcers, kidney disease, late pregnancy, heart failure, anticoagulants without a clinician. Never stack two NSAIDs.",
    ifUnavailable: "Same class, different half-life. If a branded gel is missing, diclofenac topical generics are the usual pharmacy map — still not for broken skin.",
    cite: "NICE analgesia; AHA NSAID cardiovascular caution",
  },
  {
    id: "ppi",
    name: "Omeprazole class (PPIs)",
    className: "Acid suppression",
    usedFor: "Frequent heartburn, ulcer healing — short-term unless a clinician names a long-term reason.",
    how: "Usually before the first meal. Not a dessert mint. Reassess at 4–8 weeks.",
    avoid: "Alarm features (bleed, weight loss, persistent vomiting) need investigation, not another box.",
    ifUnavailable: "Omeprazole, esomeprazole, lansoprazole are the same class. Pair with a deprescribing plan, not infinite use.",
    cite: "ACG GERD guideline",
  },
  {
    id: "ah",
    name: "Cetirizine / loratadine / fexofenadine",
    className: "Second-generation antihistamine",
    usedFor: "Hay fever, hives, itchy allergic symptoms.",
    how: "Daily in season beats chasing sneezes. Less sedation than old 'first generation' tablets.",
    avoid: "Anaphylaxis is adrenaline and emergency care, not another tablet. Some people still sedate — don't drive until you know.",
    ifUnavailable: "These three are often interchangeable for many people. First-generation diphenhydramine is a worse night drug than people think.",
    cite: "AAAAI allergic rhinitis",
  },
  {
    id: "nasal",
    name: "Intranasal corticosteroid (fluticasone, budesonide, mometasone)",
    className: "Local steroid spray",
    usedFor: "Allergic rhinitis that antihistamines don't cover. Best daily, aimed correctly, for 1–2 weeks before judging.",
    how: "Nose pointing slightly out, not at the septum. They are not instant like a decongestant.",
    avoid: "Unilateral bloody discharge, or a spray that was meant as a 3-day decongestant (oxymetazoline) used for weeks — rebound congestion.",
    ifUnavailable: "Other intranasal corticosteroids are typically interchangeable under pharmacist guidance.",
    cite: "ARIA / ENT rhinitis pathways",
  },
  {
    id: "melatonin",
    name: "Melatonin",
    className: "Chronobiotic (timing signal)",
    usedFor: "Jet lag and some circadian delay — low dose, correctly timed. It is not a strong sedative.",
    how: "Discuss with a clinician if you take other medicines. Quality of OTC products varies by country.",
    avoid: "Do not mix with alcohol as a 'stack'. Not first-line for chronic insomnia — that is CBT-I (ACP).",
    ifUnavailable: "A consistent dark, cool room and a fixed wake time outperform a random milligram from a petrol station.",
    cite: "AASM melatonin statements; ACP insomnia",
  },
  {
    id: "ors",
    name: "Oral rehydration solution",
    className: "Electrolyte-glucose solution",
    usedFor: "Watery diarrhoea, heat, vomiting when you can keep sips down.",
    how: "Small and frequent. Sports drinks are not the same formula (too little sodium, too much sugar).",
    avoid: "Blood in stool, high fever, confusion, or inability to keep fluid — clinic, not more powder.",
    ifUnavailable: "WHO-style ORS packets are the reference. A homemade mix is a last resort and easy to get wrong — prefer a packet.",
    cite: "WHO diarrhoeal disease; CDC traveler advice",
  },
  {
    id: "fiber",
    name: "Psyllium husk",
    className: "Soluble fiber",
    usedFor: "Constipation and some IBS-C; also a modest LDL lever with diet.",
    how: "Start low. Water. Titrate. Gas is common in week one.",
    avoid: "Swallowing difficulty, suspected obstruction. Not a substitute for blood in stool being checked.",
    ifUnavailable: "Other bulk-forming fibers exist. Prunes and kiwifruit have trial data too.",
    cite: "ACG constipation; fiber reviews",
  },
  {
    id: "vitd",
    name: "Vitamin D",
    className: "Hormone precursor / supplement",
    usedFor: "Documented deficiency, limited sun, some bone and immune contexts — test, don't guess a megadose.",
    how: "Food first (oily fish, fortified). A clinician interprets 25-OH D. Typical OTC doses are not a tan in a bottle.",
    avoid: "Very high unsupervised doses can raise calcium. Not a treatment for fatigue until deficiency is shown.",
    ifUnavailable: "The IU on the label matter more than the brand. D3 is the usual OTC form.",
    cite: "Endocrine Society vitamin D; NICE",
  },
  {
    id: "mag",
    name: "Magnesium (glycinate / citrate)",
    className: "Mineral",
    usedFor: "Often discussed for constipation (citrate) and as a migraine-prevention adjunct (glycinate) — evidence mixed, harm usually low if kidneys are well.",
    how: "With food. Citrate loosens stool; glycinate is quieter. Kidney disease: clinician only.",
    avoid: "Do not stack with other laxatives blindly. Not a sleep drug, though some people feel calmer.",
    ifUnavailable: "Oxide is cheap and poorly absorbed. Match the salt to the job, not the influencer.",
    cite: "AAN/AHS migraine prevention; ACG constipation",
  },
  {
    id: "hc",
    name: "Hydrocortisone 1% cream",
    className: "Low-potency topical steroid",
    usedFor: "Short bursts of itchy, inflamed skin (insect bite, mild eczema patch).",
    how: "Thin layer, few days, then moisturizer. Face, groin, and children: more caution — pharmacist or clinician.",
    avoid: "Infected skin, unexplained rash with fever, or weeks of daily face use.",
    ifUnavailable: "Other 1% hydrocortisone tubes are the same molecule. Stronger steroids are not a silent swap.",
    cite: "NICE eczema; AAD topical steroid advice",
  },
  {
    id: "adapalene",
    name: "Adapalene 0.1% / benzoyl peroxide",
    className: "Retinoid + antibacterial (acne)",
    usedFor: "Comedonal and inflammatory acne. Foundations that still outperform most serums.",
    how: "Pea-size retinoid at night, moisturizer, SPF by day. Benzoyl peroxide as a spot or wash. Six weeks before judging.",
    avoid: "Pregnancy for retinoids. Don't stack five acids. Irritation is not a glow.",
    ifUnavailable: "If a branded retinoid is missing, adapalene 0.1% OTC is the usual cousin. Benzoyl peroxide generics are everywhere.",
    cite: "AAD acne guideline",
  },
  {
    id: "alginate",
    name: "Alginate / antacid (Gaviscon-class)",
    className: "Reflux barrier",
    usedFor: "Occasional heartburn, especially after meals or at night, when you also raise the head of the bed.",
    how: "After meals and at bedtime as labelled. Not a daily forever plan.",
    avoid: "Alarm features (bleed, weight loss, persistent vomiting) need investigation, not another mint.",
    ifUnavailable: "Alginate plus a simple antacid is the class. PPIs are a different tool — short-term unless a clinician names a reason.",
    cite: "ACG GERD guideline",
  },
  {
    id: "nrt",
    name: "Nicotine replacement (patch, gum, lozenge)",
    className: "Smoking cessation",
    usedFor: "Stopping cigarettes. Combination NRT plus counselling beats willpower speeches.",
    how: "Start on the quit day. Patch for baseline, gum/lozenge for urges. Licensed programmes exist.",
    avoid: "Continuing to smoke a full pack on a high-dose patch without advice. Vaping is not a website protocol.",
    ifUnavailable: "Patches, gum, and lozenges are interchangeable tools in a plan. Prescription medicines (varenicline, bupropion) need a clinician.",
    cite: "Cochrane tobacco; CDC cessation",
  },
  {
    id: "tears",
    name: "Preservative-free lubricating drops",
    className: "Artificial tears",
    usedFor: "Dry, tired, screen-strained eyes. Redness-reducers are not the same thing.",
    how: "Blink breaks, humidity, then drops. Refrigeration can feel nicer.",
    avoid: "Painful red eye, sudden vision change, or a 'curtain' — emergency, not another drop.",
    ifUnavailable: "Hyaluronate or carboxymethylcellulose preservative-free units are the usual map.",
    cite: "AAO dry eye",
  },
  {
    id: "simethicone",
    name: "Simethicone",
    className: "Anti-foaming (gas)",
    usedFor: "Bloating from gas that is otherwise benign.",
    how: "As labelled, often after meals. Fiber titration and a walk usually matter more.",
    avoid: "Blood, weight loss, night pain, or persistent vomiting — not gas.",
    ifUnavailable: "The molecule is the product. Peppermint oil has some IBS data; it is not for reflux-dominant people.",
    cite: "Rome IV IBS; ACG bloating",
  },
];
