export type Practice = {
  id: string;
  title: string;
  minutes: number;
  body: string;
  cite: string;
  room: string;
  image: string;
};

export const PRACTICES: Practice[] = [
  {
    id: "light",
    title: "Outdoor light in the first hour",
    minutes: 10,
    body: "Step outside shortly after waking. Outdoor illuminance, even on cloudy days, dwarfs indoor lamps and sets the circadian clock (Czeisler; Huberman Lab public notes on melanopsin).",
    cite: "Circadian photoreception literature",
    room: "/sleep",
    image: "/images/sleep-still.jpg",
  },
  {
    id: "walk",
    title: "Ten-minute walk after a meal",
    minutes: 10,
    body: "A short post-meal walk lowers the glucose curve more than remaining seated. It is not a workout. It is a metabolic habit (Reynolds et al., sports-medicine walking studies).",
    cite: "Postprandial walking trials",
    room: "/strength",
    image: "/images/strength.jpg",
  },
  {
    id: "caffeine",
    title: "Delay the first coffee 60–90 minutes",
    minutes: 1,
    body: "Cortisol is already high on waking. Waiting reduces the afternoon crash for many people. If you sleep well with immediate coffee, keep it — this is a lever, not a religion.",
    cite: "Adenosine / caffeine pharmacokinetics",
    room: "/sleep",
    image: "/images/sleep.jpg",
  },
  {
    id: "deep",
    title: "One 50-minute deep block",
    minutes: 50,
    body: "Phone in another room. One hard thing. Ninety minutes is classic ultradian, fifty is enough to start (Newport, Deep Work).",
    cite: "Deep Work — Cal Newport",
    room: "/mind",
    image: "/images/mind.jpg",
  },
  {
    id: "two-minutes",
    title: "The two-minute start",
    minutes: 2,
    body: "You do not rise to goals. You fall to systems. Make the first action tiny enough that resistance looks silly (Clear; Fogg).",
    cite: "Atomic Habits — James Clear",
    room: "/mind",
    image: "/images/career.jpg",
  },
  {
    id: "worry",
    title: "Paper worry dump",
    minutes: 10,
    body: "Write every loop once. Capture is not rumination. Scheduled worry beats 1am negotiation with the ceiling.",
    cite: "Stimulus control / CBT-I worry time",
    room: "/mind",
    image: "/images/library.jpg",
  },
  {
    id: "bid",
    title: "Turn toward one bid",
    minutes: 5,
    body: "When someone says 'look at this,' look. Gottman: turning toward small reaches predicts stability more than grand gestures.",
    cite: "Gottman Institute",
    room: "/relations",
    image: "/images/relations.jpg",
  },
  {
    id: "protein",
    title: "Protein at breakfast",
    minutes: 8,
    body: "20–30 g in the first meal reduces later grazing for many people. Eggs, yogurt, tofu, leftovers — not a pastry with a protein claim.",
    cite: "Protein leverage / satiety literature",
    room: "/nutrition",
    image: "/images/food-table.jpg",
  },
  {
    id: "shutdown",
    title: "Shutdown ritual",
    minutes: 8,
    body: "Write tomorrow's first task. Close the laptop. Say the day is over out loud if you must. Knowledge work leaks without a border (Newport).",
    cite: "Deep Work — shutdown ritual",
    room: "/career",
    image: "/images/career.jpg",
  },
  {
    id: "breath",
    title: "Physiological sigh × 3",
    minutes: 2,
    body: "Double inhale through the nose, long exhale through the mouth. Fast down-regulation when the body is spun up. Not a treatment for panic disorder.",
    cite: "Huberman / Ramirez breathing notes; clinical caution",
    room: "/mind",
    image: "/images/mind.jpg",
  },
  {
    id: "load",
    title: "Two strength sessions this week",
    minutes: 40,
    body: "Squat or sit-to-stand, hinge, push, pull, carry. Soreness is not the metric. What you can lift in eight weeks is (ACSM; Attia).",
    cite: "ACSM; Outlive — Attia",
    room: "/strength",
    image: "/images/strength.jpg",
  },
  {
    id: "news",
    title: "One digest, not a feed",
    minutes: 15,
    body: "The world is serious. Your cortisol does not help distant fires. One written briefing, then close it. Act locally where you have agency.",
    cite: "Attention economy; stoic split (Seneca)",
    room: "/career",
    image: "/images/career.jpg",
  },
  {
    id: "water",
    title: "Water before the second coffee",
    minutes: 1,
    body: "Mild dehydration is an under-named headache and fatigue cause. A glass is not a cleanse. It is plumbing.",
    cite: "Hydration and cognition reviews",
    room: "/clinic",
    image: "/images/clinic.jpg",
  },
  {
    id: "spf",
    title: "Daylight SPF on the face",
    minutes: 2,
    body: "UV is the dominant cosmetic aging input you can actually control. Mineral or chemical — the one you will reapply.",
    cite: "AAD photoprotection",
    room: "/aesthetics",
    image: "/images/aesthetics.jpg",
  },
  {
    id: "steps",
    title: "Eight thousand steps, not a marathon",
    minutes: 40,
    body: "Step counts are a crude but honest proxy. Most of the mortality curve's steep part is leaving the chair. Eight thousand is a useful adult target, not a religion.",
    cite: "Step-count cohort studies (Paluch et al.)",
    room: "/strength",
    image: "/images/strength.jpg",
  },
  {
    id: "dim",
    title: "Dim the last hour",
    minutes: 5,
    body: "Overhead LEDs at 10pm are a circadian insult. Lamps low, screens out of the bed, phone charging in another room.",
    cite: "Czeisler; melanopsin photoreception",
    room: "/sleep",
    image: "/images/sleep-still.jpg",
  },
  {
    id: "sitstand",
    title: "Sit-to-stand × 10",
    minutes: 3,
    body: "From a chair, unassisted if you can. This is the beginning of a squat. Do it while the kettle boils.",
    cite: "ACSM older-adult; sit-to-stand as function",
    room: "/strength",
    image: "/images/strength.jpg",
  },
  {
    id: "meal",
    title: "One undistracted meal",
    minutes: 20,
    body: "No feed. Chew. Notice fullness. A standing weekly meal with humans is even better — loneliness is physiology (Holt-Lunstad).",
    cite: "Holt-Lunstad; mindful-eating literature",
    room: "/relations",
    image: "/images/food-table.jpg",
  },
  {
    id: "next-action",
    title: "Name the next physical action",
    minutes: 2,
    body: "Not 'work on the project.' Open the document. Put on shoes. Procrastination dies at the first physical move (Steel / Pychyl).",
    cite: "Implementation intentions — Gollwitzer",
    room: "/mind",
    image: "/images/mind.jpg",
  },
  {
    id: "walk20",
    title: "Twenty-minute brisk walk",
    minutes: 20,
    body: "Mood biology, blood pressure, and the glucose curve all move. It is not cross-training. It is a drug with a boring name.",
    cite: "NICE depression; physical activity guidelines",
    room: "/mind",
    image: "/images/mind.jpg",
  },
];

export function practiceOfDay(date = new Date()) {
  const i = Math.abs(date.getFullYear() * 366 + date.getMonth() * 31 + date.getDate()) % PRACTICES.length;
  return PRACTICES[i];
}
