export type Recipe = {
  id: string;
  name: string;
  minutes: number;
  serves: number;
  diet: Array<"omnivore" | "mediterranean" | "vegetarian" | "vegan" | "low-carb">;
  tags: string[];
  why: string;
  ingredients: string[];
  method: string[];
  organic: string;
  kcal?: string;
  tier: "free" | "pro" | "plus";
};

export const RECIPES: Recipe[] = [
  {
    id: "oat-olive",
    name: "Dawn oats, olive, and citrus",
    minutes: 12,
    serves: 1,
    diet: ["mediterranean", "vegetarian", "omnivore"],
    tags: ["breakfast", "fiber", "steady glucose"],
    why: "Beta-glucan plus protein blunts the morning glucose spike better than juice and pastry (Jenkins; oat literature).",
    ingredients: [
      "50 g rolled oats",
      "180 ml unsweetened milk or fortified soy",
      "15 g walnuts",
      "10 ml extra-virgin olive oil",
      "½ orange, segmented",
      "Pinch cinnamon",
      "Optional: 100 g Greek yogurt on the side",
    ],
    method: [
      "Simmer oats in milk 6–8 minutes until creamy.",
      "Stir in olive oil off heat — fat slows the glucose curve and carries flavor.",
      "Top with walnuts, orange, cinnamon.",
    ],
    organic: "Prefer organic oats and citrus if you eat the peel. Olive oil: harvest date on the bottle, not a lifestyle label.",
    kcal: "~420 kcal with yogurt",
    tier: "free",
  },
  {
    id: "lentil-bowl",
    name: "Black lentil, herb, and lemon bowl",
    minutes: 35,
    serves: 2,
    diet: ["mediterranean", "vegetarian", "vegan", "omnivore"],
    tags: ["lunch", "iron", "fiber"],
    why: "Pulses are the cheapest longevity food in PREDIMED-style patterns.",
    ingredients: [
      "160 g dry black beluga or Puy lentils",
      "1 bay leaf",
      "200 g chopped cucumber",
      "150 g cherry tomatoes",
      "40 g parsley + mint",
      "30 ml extra-virgin olive oil",
      "20 ml lemon juice",
      "1 garlic clove, grated",
      "Salt, pepper, sumac",
    ],
    method: [
      "Simmer lentils with bay until just tender, 18–22 min. Drain, cool 5 min.",
      "Fold through vegetables, herbs, oil, lemon, garlic.",
      "Salt like you mean it. Eat warm or cold.",
    ],
    organic: "Herbs and tomatoes are high on residue lists — worth organic if budget allows. Lentils: conventional is fine; rinse well.",
    kcal: "~380 kcal / plate",
    tier: "free",
  },
  {
    id: "fish-greens",
    name: "Weeknight fish, bitter greens, lemon",
    minutes: 22,
    serves: 2,
    diet: ["mediterranean", "omnivore", "low-carb"],
    tags: ["dinner", "omega-3", "protein"],
    why: "Oily fish 2×/week is one of the few food-as-medicine recommendations with outcome data (AHA).",
    ingredients: ["360 g salmon, sardines, or mackerel", "300 g cavolo nero or spinach", "20 ml olive oil, split", "1 lemon", "Chili flake, salt"],
    method: [
      "Salt fish. Pan 3–5 min skin-side, 2 min flesh, until just opaque.",
      "Wilt greens in remaining oil 2 min with chili.",
      "Lemon over everything. Potatoes or nothing, depending on your fuel goal.",
    ],
    organic: "Smaller fish (sardines) are lower mercury. Frozen wild or well-certified farmed both beat no fish.",
    kcal: "~480 kcal / plate",
    tier: "free",
  },
  {
    id: "egg-veg",
    name: "Slow eggs, leftover vegetables",
    minutes: 15,
    serves: 1,
    diet: ["omnivore", "mediterranean", "vegetarian", "low-carb"],
    tags: ["breakfast", "protein", "budget"],
    why: "Eggs are a complete protein with choline for brain membranes. Dietary cholesterol is not the 1980s villain for most people.",
    ingredients: ["2–3 eggs", "150 g leftover cooked vegetables", "10 ml olive oil or 5 g butter", "Herbs, pepper, chili"],
    method: ["Warm vegetables in fat.", "Low heat, eggs in, stir until just set — custard, not rubber.", "Herbs. Eat slowly."],
    organic: "Pasture eggs if you can. Frozen organic vegetables are often more nutrient-dense than tired 'fresh'.",
    kcal: "~320 kcal",
    tier: "free",
  },
  {
    id: "yogurt-lab",
    name: "Savory yogurt, cucumber, olive, seed",
    minutes: 8,
    serves: 1,
    diet: ["mediterranean", "vegetarian", "omnivore"],
    tags: ["snack", "protein", "gut"],
    why: "Fermented dairy is associated with better metabolic markers than sugar-yogurt desserts.",
    ingredients: ["200 g plain Greek yogurt or skyr", "80 g cucumber, grated and squeezed", "8 g extra-virgin olive oil", "10 g pumpkin seeds", "Dill, salt, black pepper"],
    method: ["Mix yogurt, cucumber, salt, dill.", "Oil and seeds on top. This is lunch, not a garnish."],
    organic: "Plain yogurt with live cultures. Skip fruit-on-the-bottom — it is dessert.",
    kcal: "~280 kcal",
    tier: "free",
  },
  {
    id: "chickpea-stew",
    name: "Tomato chickpea stew with greens",
    minutes: 40,
    serves: 4,
    diet: ["vegan", "vegetarian", "mediterranean", "omnivore"],
    tags: ["batch", "fiber", "iron"],
    why: "Batch cooking is a discipline tool. Decision fatigue at 8pm is why people order beige food.",
    ingredients: [
      "2 cans chickpeas (480 g drained) or 250 g dry, cooked",
      "400 g crushed tomatoes",
      "1 onion, 3 garlic",
      "200 g spinach",
      "30 ml olive oil",
      "Cumin, smoked paprika, salt",
      "Lemon to finish",
    ],
    method: ["Onion in oil 8 min. Garlic 1 min. Spices 30 sec.", "Tomatoes, chickpeas, 150 ml water. 20 min.", "Spinach in. Lemon. Freeze two portions."],
    organic: "Canned tomatoes: BPA-free linings when you can. Chickpeas: dry organic is cheap per plate.",
    kcal: "~350 kcal / bowl",
    tier: "free",
  },
  {
    id: "sardine-toast",
    name: "Sardine toast, lemon, chili",
    minutes: 8,
    serves: 1,
    diet: ["mediterranean", "omnivore"],
    tags: ["lunch", "omega-3", "budget"],
    why: "Canned sardines are EPA/DHA, calcium (if bones), and protein for the price of a coffee.",
    ingredients: ["1 can sardines in olive oil (≈90 g drained)", "1 slice dense rye or sourdough", "Lemon, chili, parsley", "Optional: 40 g tomato"],
    method: ["Toast bread.", "Mash sardines with lemon and chili. Pile on. Parsley."],
    organic: "Sardines: small fish, low mercury. Bread: look for whole grain and a short ingredient list.",
    kcal: "~390 kcal",
    tier: "free",
  },
  {
    id: "miso-greens",
    name: "Miso broth, greens, and tofu",
    minutes: 12,
    serves: 1,
    diet: ["vegan", "vegetarian", "omnivore", "low-carb"],
    tags: ["dinner", "evening", "salt-aware"],
    why: "A hot, high-protein bowl at night beats grazing. Fermented soybean paste is a flavor engine, not a miracle.",
    ingredients: ["12 g white miso", "400 ml water or light stock", "150 g silken or firm tofu", "80 g spinach or bok choy", "Spring onion, sesame"],
    method: ["Heat water. Whisk miso off the boil so you keep the live culture.", "Tofu and greens 2 min. Onion, sesame."],
    organic: "Organic tofu if GM soy bothers you. Miso: refrigerated, unpasteurized when you can.",
    kcal: "~220 kcal",
    tier: "free",
  },
  {
    id: "chicken-tray",
    name: "Tray chicken, olive, and roots",
    minutes: 50,
    serves: 4,
    diet: ["omnivore", "mediterranean", "low-carb"],
    tags: ["batch", "protein", "weeknight"],
    why: "One pan, leftover lunches, protein for training days. Skin-on for flavor; eat the vegetables first.",
    ingredients: [
      "800 g chicken thighs, bone-in",
      "600 g mixed roots or cauliflower",
      "1 red onion",
      "30 ml olive oil",
      "Lemon, rosemary, salt",
    ],
    method: ["220°C. Toss vegetables in oil and salt. Chicken on top, skin up.", "35–45 min until juices run clear.", "Rest 5. Lemon over."],
    organic: "If you buy one organic animal food, make it this. Otherwise, well-cooked conventional plus plants still wins.",
    kcal: "~520 kcal / plate",
    tier: "free",
  },
  {
    id: "kefir-bowl",
    name: "Kefir, berries, seed, cacao nib",
    minutes: 5,
    serves: 1,
    diet: ["vegetarian", "omnivore", "mediterranean"],
    tags: ["breakfast", "gut", "polyphenols"],
    why: "Kefir is a diverse fermented dairy. Berries beat juice for fiber and a slower sugar curve.",
    ingredients: ["250 ml plain kefir", "80 g mixed berries (frozen is fine)", "15 g mixed seeds", "5 g cacao nibs"],
    method: ["Bowl. Berries in. Seeds. Nibs. No honey unless you trained hard."],
    organic: "Berries are often high-residue — a reasonable organic spend. Kefir: live cultures, unsweetened.",
    kcal: "~310 kcal",
    tier: "free",
  },
  {
    id: "bean-potato",
    name: "White beans, rosemary, roast potato",
    minutes: 45,
    serves: 3,
    diet: ["vegan", "vegetarian", "mediterranean", "omnivore"],
    tags: ["dinner", "fiber", "budget"],
    why: "Potatoes are not the enemy; frying and isolation from protein are. Resistant starch rises as they cool.",
    ingredients: ["500 g potatoes, chunks", "1 can cannellini (240 g drained)", "30 ml olive oil", "Rosemary, garlic, salt", "A handful of rocket"],
    method: ["Roast potatoes 200°C / 30 min.", "Warm beans in oil, garlic, rosemary.", "Combine. Rocket. Eat half cold tomorrow."],
    organic: "Potatoes: conventional is usually fine if you peel or scrub. Rocket: wash well.",
    kcal: "~430 kcal / plate",
    tier: "free",
  },
  {
    id: "overnight-oat",
    name: "Overnight oat, chia, and pear",
    minutes: 8,
    serves: 1,
    diet: ["vegetarian", "vegan", "omnivore", "mediterranean"],
    tags: ["breakfast", "prep", "fiber"],
    why: "Prepared at night so 7am you is not negotiating with a pastry. Chia adds gel and omega-3 ALA (not a fish replacement).",
    ingredients: ["45 g oats", "12 g chia", "180 ml soy or milk", "1 small pear, diced", "Cinnamon"],
    method: ["Mix oats, chia, milk, cinnamon. Fridge overnight.", "Pear in the morning."],
    organic: "Pear skin holds the fiber — wash well or buy organic.",
    kcal: "~360 kcal",
    tier: "free",
  },
  {
    id: "steak-salad",
    name: "Seared steak, bitter leaf, mustard",
    minutes: 25,
    serves: 2,
    diet: ["omnivore", "low-carb", "mediterranean"],
    tags: ["dinner", "iron", "strength"],
    why: "Creatine and heme iron from meat help some training and ferritin-low people. Portion is a palm, not a platter.",
    ingredients: ["300 g sirloin or flank", "150 g mixed bitter leaves", "10 g Dijon", "15 ml olive oil + 10 ml vinegar", "Salt, pepper"],
    method: ["Salt steak 30 min ahead if you can.", "Hot pan, 2–4 min/side. Rest 5.", "Slice. Dress leaves. Meat on top."],
    organic: "If budget allows one organic animal food, make it this.",
    kcal: "~490 kcal / plate",
    tier: "free",
  },
  {
    id: "shakshuka",
    name: "Shakshuka for two",
    minutes: 30,
    serves: 2,
    diet: ["vegetarian", "mediterranean", "omnivore"],
    tags: ["brunch", "lycopene", "protein"],
    why: "Eggs in a tomato sauce is lycopene (fat-soluble — the oil matters) plus choline.",
    ingredients: ["400 g tomatoes", "1 onion, 1 pepper", "4 eggs", "20 ml olive oil", "Cumin, paprika, chili", "Parsley"],
    method: ["Onion and pepper in oil 8 min.", "Tomatoes and spices 10 min.", "Wells, eggs, lid 6–8 min. Parsley."],
    organic: "Peppers and tomatoes: organic if you eat a lot of them.",
    kcal: "~340 kcal / plate",
    tier: "free",
  },
  {
    id: "walnut-pesto",
    name: "Walnut pesto, greens, and grain",
    minutes: 20,
    serves: 2,
    diet: ["vegetarian", "vegan", "mediterranean", "omnivore"],
    tags: ["lunch", "polyphenols", "alpha-linolenic"],
    why: "Walnuts are the nut with outcome-adjacent data in PREDIMED's nut arm.",
    ingredients: ["60 g walnuts", "40 g basil or parsley", "30 ml olive oil", "1 garlic", "Lemon", "160 g cooked farro or quinoa", "100 g greens"],
    method: ["Pulse pesto. Don't pulverize to baby food.", "Warm grain, fold pesto and greens."],
    organic: "Basil is a reasonable organic spend. Walnuts: rancid is the real enemy — smell them.",
    kcal: "~520 kcal / plate",
    tier: "free",
  },
  {
    id: "liver-onions",
    name: "Calf liver, onions, lemon",
    minutes: 18,
    serves: 2,
    diet: ["omnivore", "low-carb"],
    tags: ["dinner", "iron", "vitamin A"],
    why: "Liver is a micronutrient concentrate (B12, folate, vitamin A, iron). Small portions. Not for pregnancy without a clinician.",
    ingredients: ["250 g calf or chicken liver", "2 onions", "15 ml olive oil or butter", "Lemon, salt, pepper"],
    method: ["Onions slow, 10 min.", "High heat, liver 90 seconds a side — pink inside. Lemon."],
    organic: "Organ meat from a named farm if you can. Frequency: a small serving weekly is plenty of vitamin A.",
    kcal: "~360 kcal / plate",
    tier: "pro",
  },
  {
    id: "tofu-sesame",
    name: "High-heat tofu, broccoli, sesame",
    minutes: 20,
    serves: 2,
    diet: ["vegan", "vegetarian", "low-carb", "omnivore"],
    tags: ["dinner", "protein", "plant"],
    why: "Soy is a complete protein. Isoflavone fear is largely outdated for typical food doses.",
    ingredients: ["400 g extra-firm tofu, pressed", "300 g broccoli", "15 ml soy sauce or tamari", "10 ml sesame oil", "5 g sesame seeds", "Chili, garlic"],
    method: ["Cube tofu. Very hot pan, don't touch 3 min.", "Broccoli in, splash water, lid 2 min.", "Soy, sesame, garlic off heat."],
    organic: "Organic tofu avoids most GM soy if that matters to you.",
    kcal: "~410 kcal / plate",
    tier: "plus",
  },
  {
    id: "training-rice",
    name: "Training-day rice, egg, greens",
    minutes: 25,
    serves: 1,
    diet: ["omnivore", "vegetarian", "mediterranean"],
    tags: ["post-training", "glycogen", "protein"],
    why: "After hard sessions, carbohydrate plus protein restores glycogen and supports muscle protein synthesis (Ivy; Morton protein meta).",
    ingredients: ["180 g cooked rice", "2 eggs", "100 g greens", "15 ml olive oil or 10 g butter", "Soy or salt"],
    method: ["Rice hot. Eggs in. Greens wilted. Season."],
    organic: "Rice: vary sources; rinse. Eggs as above.",
    kcal: "~620 kcal",
    tier: "plus",
  },
  {
    id: "quinoa-carrot",
    name: "Herbed quinoa, chickpea, roasted carrot",
    minutes: 35,
    serves: 3,
    diet: ["vegan", "vegetarian", "mediterranean", "omnivore"],
    tags: ["lunch", "batch", "fiber"],
    why: "A vegan plate with complete protein when quinoa and chickpea share the bowl. Batch it on Sunday.",
    ingredients: [
      "150 g dry quinoa",
      "1 can chickpeas (240 g drained)",
      "400 g carrots, chunks",
      "30 ml olive oil",
      "Cumin, coriander, salt",
      "30 g parsley",
      "Lemon",
    ],
    method: [
      "Roast carrots 200°C / 25 min with half the oil and spices.",
      "Simmer quinoa 12 min. Drain.",
      "Fold chickpeas, carrots, parsley, lemon, remaining oil.",
    ],
    organic: "Parsley is a reasonable organic spend. Carrots: scrub well; conventional is usually fine.",
    kcal: "~420 kcal / bowl",
    tier: "free",
  },
  {
    id: "ginger-greens",
    name: "Ginger greens, garlic, and a slow egg",
    minutes: 14,
    serves: 1,
    diet: ["vegetarian", "omnivore", "low-carb", "mediterranean"],
    tags: ["dinner", "evening", "iron"],
    why: "A pan of greens is the cheapest longevity habit after walking. The egg is the protein so you do not graze later.",
    ingredients: ["200 g mixed greens", "1 garlic clove", "10 g ginger", "10 ml olive oil", "1–2 eggs", "Chili, soy or salt"],
    method: ["Oil, garlic, ginger 30 sec.", "Greens, splash of water, lid 2 min.", "Egg in a well, lid until just set."],
    organic: "Leafy greens are a high-yield organic spend if budget is tight elsewhere.",
    kcal: "~280 kcal",
    tier: "free",
  },
  {
    id: "apple-skillet",
    name: "Apple, oat, and walnut skillet",
    minutes: 18,
    serves: 2,
    diet: ["vegetarian", "vegan", "omnivore", "mediterranean"],
    tags: ["breakfast", "fiber", "polyphenols"],
    why: "Warm fruit plus oats is dessert that still has fiber. Walnuts were in PREDIMED's nut arm.",
    ingredients: ["2 apples, sliced", "40 g oats", "20 g walnuts", "10 ml olive oil or 8 g butter", "Cinnamon", "Pinch salt"],
    method: ["Apples in fat 6 min.", "Oats and walnuts 3 min.", "Cinnamon. Eat warm. Yogurt on the side if you want protein."],
    organic: "Apple skin holds the fiber — wash well or buy organic.",
    kcal: "~310 kcal / plate",
    tier: "free",
  },
  {
    id: "yogurt-bowl",
    name: "Plain yogurt, fruit, and 20 g walnuts",
    minutes: 6,
    serves: 1,
    diet: ["vegetarian", "omnivore", "mediterranean"],
    tags: ["breakfast", "protein", "fast"],
    why: "A breakfast you can log in grams. Fruit is the sweet. Walnuts were in PREDIMED's nut arm.",
    ingredients: ["200 g plain yogurt", "120 g berries or chopped fruit", "20 g walnuts", "Pinch cinnamon"],
    method: ["Bowl. Yogurt. Fruit. Nuts. That is the recipe."],
    organic: "Berries are a high-yield organic spend if you eat them daily.",
    kcal: "~320 kcal",
    tier: "free",
  },
  {
    id: "sheet-broccoli",
    name: "Sheet-pan salmon, broccoli, lemon",
    minutes: 22,
    serves: 2,
    diet: ["omnivore", "mediterranean", "low-carb"],
    tags: ["dinner", "omega-3", "weeknight"],
    why: "Oily fish plus a brassica. The AHA cares about the fish more than the garnish.",
    ingredients: ["2 salmon fillets ~140 g each", "400 g broccoli", "20 ml olive oil", "Lemon", "Salt, pepper"],
    method: ["220°C. Broccoli and oil 8 min. Fish on the tray 10–12 min. Lemon."],
    organic: "Broccoli: wash well. Fish: smaller species, a named fishery if you can.",
    kcal: "~480 kcal / plate",
    tier: "free",
  },
];

export const MEASURES = [
  { from: "1 cup oats", to: "90 g" },
  { from: "1 cup cooked lentils", to: "200 g" },
  { from: "1 cup cooked rice", to: "160 g" },
  { from: "1 cup cooked quinoa", to: "185 g" },
  { from: "1 tbsp olive oil", to: "15 ml / 14 g" },
  { from: "1 tsp salt", to: "5 g" },
  { from: "1 tbsp honey", to: "21 g" },
  { from: "palm protein", to: "≈ 20–30 g cooked meat/fish/tofu" },
  { from: "fist vegetables", to: "≈ 80–100 g cooked" },
  { from: "thumb fats", to: "≈ 10–15 g oil/nut butter" },
  { from: "1 scoop protein powder", to: "check the label — usually 20–30 g protein" },
  { from: "1 medium egg", to: "≈ 50 g (6 g protein)" },
];

export const CONVERTER = [
  { id: "oil", name: "Olive oil", unit: "tbsp", grams: 14 },
  { id: "oats", name: "Rolled oats", unit: "cup", grams: 90 },
  { id: "rice", name: "Cooked rice", unit: "cup", grams: 160 },
  { id: "lentil", name: "Cooked lentils", unit: "cup", grams: 200 },
  { id: "flour", name: "Wheat flour", unit: "cup", grams: 120 },
  { id: "sugar", name: "Sugar", unit: "tbsp", grams: 12 },
  { id: "yogurt", name: "Greek yogurt", unit: "cup", grams: 245 },
  { id: "nuts", name: "Walnuts", unit: "cup", grams: 100 },
];
