/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AestheticsRouteImport } from './routes/aesthetics'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MindRouteImport } from './routes/mind'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as PacketRouteImport } from './routes/packet'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RelationsRouteImport } from './routes/relations'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as StrengthRouteImport } from './routes/strength'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AestheticsRoute = AestheticsRouteImport.update({
  id: '/aesthetics',
  path: '/aesthetics',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MindRoute = MindRouteImport.update({
  id: '/mind',
  path: '/mind',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketRoute = PacketRouteImport.update({
  id: '/packet',
  path: '/packet',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationsRoute = RelationsRouteImport.update({
  id: '/relations',
  path: '/relations',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const StrengthRoute = StrengthRouteImport.update({
  id: '/strength',
  path: '/strength',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aesthetics': typeof AestheticsRoute
  '/career': typeof CareerRoute
  '/clinic': typeof ClinicRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/intake': typeof IntakeRoute
  '/kitchen': typeof KitchenRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mind': typeof MindRoute
  '/notes': typeof NotesRoute
  '/nutrition': typeof NutritionRoute
  '/packet': typeof PacketRoute
  '/payouts': typeof PayoutsRoute
  '/pricing': typeof PricingRoute
  '/progress': typeof ProgressRoute
  '/relations': typeof RelationsRoute
  '/sleep': typeof SleepRoute
  '/strength': typeof StrengthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aesthetics': typeof AestheticsRoute
  '/career': typeof CareerRoute
  '/clinic': typeof ClinicRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/intake': typeof IntakeRoute
  '/kitchen': typeof KitchenRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mind': typeof MindRoute
  '/notes': typeof NotesRoute
  '/nutrition': typeof NutritionRoute
  '/packet': typeof PacketRoute
  '/payouts': typeof PayoutsRoute
  '/pricing': typeof PricingRoute
  '/progress': typeof ProgressRoute
  '/relations': typeof RelationsRoute
  '/sleep': typeof SleepRoute
  '/strength': typeof StrengthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aesthetics': typeof AestheticsRoute
  '/career': typeof CareerRoute
  '/clinic': typeof ClinicRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/intake': typeof IntakeRoute
  '/kitchen': typeof KitchenRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mind': typeof MindRoute
  '/notes': typeof NotesRoute
  '/nutrition': typeof NutritionRoute
  '/packet': typeof PacketRoute
  '/payouts': typeof PayoutsRoute
  '/pricing': typeof PricingRoute
  '/progress': typeof ProgressRoute
  '/relations': typeof RelationsRoute
  '/sleep': typeof SleepRoute
  '/strength': typeof StrengthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aesthetics'
    | '/career'
    | '/clinic'
    | '/dashboard'
    | '/faq'
    | '/intake'
    | '/kitchen'
    | '/library'
    | '/login'
    | '/mind'
    | '/notes'
    | '/nutrition'
    | '/packet'
    | '/payouts'
    | '/pricing'
    | '/progress'
    | '/relations'
    | '/sleep'
    | '/strength'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aesthetics'
    | '/career'
    | '/clinic'
    | '/dashboard'
    | '/faq'
    | '/intake'
    | '/kitchen'
    | '/library'
    | '/login'
    | '/mind'
    | '/notes'
    | '/nutrition'
    | '/packet'
    | '/payouts'
    | '/pricing'
    | '/progress'
    | '/relations'
    | '/sleep'
    | '/strength'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/aesthetics'
    | '/career'
    | '/clinic'
    | '/dashboard'
    | '/faq'
    | '/intake'
    | '/kitchen'
    | '/library'
    | '/login'
    | '/mind'
    | '/notes'
    | '/nutrition'
    | '/packet'
    | '/payouts'
    | '/pricing'
    | '/progress'
    | '/relations'
    | '/sleep'
    | '/strength'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AestheticsRoute: typeof AestheticsRoute
  CareerRoute: typeof CareerRoute
  ClinicRoute: typeof ClinicRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  IntakeRoute: typeof IntakeRoute
  KitchenRoute: typeof KitchenRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MindRoute: typeof MindRoute
  NotesRoute: typeof NotesRoute
  NutritionRoute: typeof NutritionRoute
  PacketRoute: typeof PacketRoute
  PayoutsRoute: typeof PayoutsRoute
  PricingRoute: typeof PricingRoute
  ProgressRoute: typeof ProgressRoute
  RelationsRoute: typeof RelationsRoute
  SleepRoute: typeof SleepRoute
  StrengthRoute: typeof StrengthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aesthetics': {
      id: '/aesthetics'
      path: '/aesthetics'
      fullPath: '/aesthetics'
      preLoaderRoute: typeof AestheticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mind': {
      id: '/mind'
      path: '/mind'
      fullPath: '/mind'
      preLoaderRoute: typeof MindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packet': {
      id: '/packet'
      path: '/packet'
      fullPath: '/packet'
      preLoaderRoute: typeof PacketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relations': {
      id: '/relations'
      path: '/relations'
      fullPath: '/relations'
      preLoaderRoute: typeof RelationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strength': {
      id: '/strength'
      path: '/strength'
      fullPath: '/strength'
      preLoaderRoute: typeof StrengthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AestheticsRoute: AestheticsRoute,
  CareerRoute: CareerRoute,
  ClinicRoute: ClinicRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  IntakeRoute: IntakeRoute,
  KitchenRoute: KitchenRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MindRoute: MindRoute,
  NotesRoute: NotesRoute,
  NutritionRoute: NutritionRoute,
  PacketRoute: PacketRoute,
  PayoutsRoute: PayoutsRoute,
  PricingRoute: PricingRoute,
  ProgressRoute: ProgressRoute,
  RelationsRoute: RelationsRoute,
  SleepRoute: SleepRoute,
  StrengthRoute: StrengthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
